System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "main.js",
      "npm:codemirror@5.6.0",
      "github:angular/bower-angular@1.4.4",
      "npm:highlight.js@8.7.0",
      "npm:meta-marked@0.3.3",
      "npm:codemirror@5.6.0/mode/gfm/gfm",
      "npm:codemirror@5.6.0/addon/edit/closebrackets",
      "npm:highlight.js@8.7.0/lib/index",
      "npm:meta-marked@0.3.3/lib/meta-marked",
      "npm:codemirror@5.6.0/addon/mode/overlay",
      "npm:codemirror@5.6.0/mode/markdown/markdown",
      "npm:codemirror@5.6.0/lib/codemirror",
      "github:angular/bower-angular@1.4.4/angular",
      "npm:highlight.js@8.7.0/lib/languages/1c",
      "github:jspm/nodelibs-process@0.1.1",
      "npm:highlight.js@8.7.0/lib/highlight",
      "npm:highlight.js@8.7.0/lib/languages/actionscript",
      "npm:highlight.js@8.7.0/lib/languages/apache",
      "npm:highlight.js@8.7.0/lib/languages/applescript",
      "npm:highlight.js@8.7.0/lib/languages/armasm",
      "npm:highlight.js@8.7.0/lib/languages/asciidoc",
      "npm:highlight.js@8.7.0/lib/languages/xml",
      "npm:highlight.js@8.7.0/lib/languages/aspectj",
      "npm:highlight.js@8.7.0/lib/languages/autohotkey",
      "npm:highlight.js@8.7.0/lib/languages/avrasm",
      "npm:highlight.js@8.7.0/lib/languages/axapta",
      "npm:highlight.js@8.7.0/lib/languages/autoit",
      "npm:highlight.js@8.7.0/lib/languages/brainfuck",
      "npm:highlight.js@8.7.0/lib/languages/bash",
      "npm:highlight.js@8.7.0/lib/languages/cal",
      "npm:highlight.js@8.7.0/lib/languages/capnproto",
      "npm:highlight.js@8.7.0/lib/languages/ceylon",
      "npm:highlight.js@8.7.0/lib/languages/clojure",
      "npm:highlight.js@8.7.0/lib/languages/cmake",
      "npm:highlight.js@8.7.0/lib/languages/clojure-repl",
      "npm:highlight.js@8.7.0/lib/languages/coffeescript",
      "npm:highlight.js@8.7.0/lib/languages/cpp",
      "npm:highlight.js@8.7.0/lib/languages/cs",
      "npm:highlight.js@8.7.0/lib/languages/css",
      "npm:highlight.js@8.7.0/lib/languages/d",
      "npm:highlight.js@8.7.0/lib/languages/markdown",
      "npm:highlight.js@8.7.0/lib/languages/dart",
      "npm:highlight.js@8.7.0/lib/languages/delphi",
      "npm:highlight.js@8.7.0/lib/languages/diff",
      "npm:highlight.js@8.7.0/lib/languages/django",
      "npm:highlight.js@8.7.0/lib/languages/dns",
      "npm:highlight.js@8.7.0/lib/languages/dockerfile",
      "npm:highlight.js@8.7.0/lib/languages/dos",
      "npm:highlight.js@8.7.0/lib/languages/dust",
      "npm:highlight.js@8.7.0/lib/languages/elixir",
      "npm:highlight.js@8.7.0/lib/languages/elm",
      "npm:highlight.js@8.7.0/lib/languages/ruby",
      "npm:highlight.js@8.7.0/lib/languages/erb",
      "npm:highlight.js@8.7.0/lib/languages/erlang-repl",
      "npm:highlight.js@8.7.0/lib/languages/erlang",
      "npm:highlight.js@8.7.0/lib/languages/fix",
      "npm:highlight.js@8.7.0/lib/languages/fortran",
      "npm:highlight.js@8.7.0/lib/languages/fsharp",
      "npm:highlight.js@8.7.0/lib/languages/gcode",
      "npm:highlight.js@8.7.0/lib/languages/gherkin",
      "npm:highlight.js@8.7.0/lib/languages/go",
      "npm:highlight.js@8.7.0/lib/languages/glsl",
      "npm:highlight.js@8.7.0/lib/languages/gradle",
      "npm:highlight.js@8.7.0/lib/languages/groovy",
      "npm:highlight.js@8.7.0/lib/languages/haml",
      "npm:highlight.js@8.7.0/lib/languages/handlebars",
      "npm:highlight.js@8.7.0/lib/languages/haskell",
      "npm:highlight.js@8.7.0/lib/languages/haxe",
      "npm:highlight.js@8.7.0/lib/languages/http",
      "npm:highlight.js@8.7.0/lib/languages/inform7",
      "npm:highlight.js@8.7.0/lib/languages/ini",
      "npm:highlight.js@8.7.0/lib/languages/java",
      "npm:highlight.js@8.7.0/lib/languages/javascript",
      "npm:highlight.js@8.7.0/lib/languages/json",
      "npm:highlight.js@8.7.0/lib/languages/julia",
      "npm:highlight.js@8.7.0/lib/languages/kotlin",
      "npm:highlight.js@8.7.0/lib/languages/lasso",
      "npm:highlight.js@8.7.0/lib/languages/less",
      "npm:highlight.js@8.7.0/lib/languages/lisp",
      "npm:highlight.js@8.7.0/lib/languages/livescript",
      "npm:highlight.js@8.7.0/lib/languages/livecodeserver",
      "npm:highlight.js@8.7.0/lib/languages/lua",
      "npm:highlight.js@8.7.0/lib/languages/makefile",
      "npm:highlight.js@8.7.0/lib/languages/matlab",
      "npm:highlight.js@8.7.0/lib/languages/mel",
      "npm:highlight.js@8.7.0/lib/languages/mathematica",
      "npm:highlight.js@8.7.0/lib/languages/mercury",
      "npm:highlight.js@8.7.0/lib/languages/mizar",
      "npm:highlight.js@8.7.0/lib/languages/perl",
      "npm:highlight.js@8.7.0/lib/languages/mojolicious",
      "npm:highlight.js@8.7.0/lib/languages/monkey",
      "npm:highlight.js@8.7.0/lib/languages/nginx",
      "npm:highlight.js@8.7.0/lib/languages/nimrod",
      "npm:highlight.js@8.7.0/lib/languages/nix",
      "npm:highlight.js@8.7.0/lib/languages/nsis",
      "npm:highlight.js@8.7.0/lib/languages/objectivec",
      "npm:highlight.js@8.7.0/lib/languages/ocaml",
      "npm:highlight.js@8.7.0/lib/languages/openscad",
      "npm:highlight.js@8.7.0/lib/languages/oxygene",
      "npm:highlight.js@8.7.0/lib/languages/parser3",
      "npm:highlight.js@8.7.0/lib/languages/pf",
      "npm:highlight.js@8.7.0/lib/languages/php",
      "npm:highlight.js@8.7.0/lib/languages/powershell",
      "npm:highlight.js@8.7.0/lib/languages/processing",
      "npm:highlight.js@8.7.0/lib/languages/profile",
      "npm:highlight.js@8.7.0/lib/languages/prolog",
      "npm:highlight.js@8.7.0/lib/languages/protobuf",
      "npm:highlight.js@8.7.0/lib/languages/puppet",
      "npm:highlight.js@8.7.0/lib/languages/python",
      "npm:highlight.js@8.7.0/lib/languages/q",
      "npm:highlight.js@8.7.0/lib/languages/r",
      "npm:highlight.js@8.7.0/lib/languages/rib",
      "npm:highlight.js@8.7.0/lib/languages/roboconf",
      "npm:highlight.js@8.7.0/lib/languages/rsl",
      "npm:highlight.js@8.7.0/lib/languages/ruleslanguage",
      "npm:highlight.js@8.7.0/lib/languages/rust",
      "npm:highlight.js@8.7.0/lib/languages/scala",
      "npm:highlight.js@8.7.0/lib/languages/scheme",
      "npm:highlight.js@8.7.0/lib/languages/scilab",
      "npm:highlight.js@8.7.0/lib/languages/scss",
      "npm:highlight.js@8.7.0/lib/languages/smali",
      "npm:highlight.js@8.7.0/lib/languages/smalltalk",
      "npm:highlight.js@8.7.0/lib/languages/sml",
      "npm:highlight.js@8.7.0/lib/languages/sql",
      "npm:highlight.js@8.7.0/lib/languages/step21",
      "npm:highlight.js@8.7.0/lib/languages/stata",
      "npm:highlight.js@8.7.0/lib/languages/stylus",
      "npm:highlight.js@8.7.0/lib/languages/swift",
      "npm:highlight.js@8.7.0/lib/languages/tcl",
      "npm:highlight.js@8.7.0/lib/languages/tex",
      "npm:highlight.js@8.7.0/lib/languages/thrift",
      "npm:highlight.js@8.7.0/lib/languages/tp",
      "npm:highlight.js@8.7.0/lib/languages/twig",
      "npm:highlight.js@8.7.0/lib/languages/typescript",
      "npm:highlight.js@8.7.0/lib/languages/vala",
      "npm:highlight.js@8.7.0/lib/languages/vbnet",
      "npm:highlight.js@8.7.0/lib/languages/vbscript",
      "npm:highlight.js@8.7.0/lib/languages/vbscript-html",
      "npm:highlight.js@8.7.0/lib/languages/verilog",
      "npm:highlight.js@8.7.0/lib/languages/vhdl",
      "npm:highlight.js@8.7.0/lib/languages/vim",
      "npm:highlight.js@8.7.0/lib/languages/xl",
      "npm:highlight.js@8.7.0/lib/languages/x86asm",
      "npm:highlight.js@8.7.0/lib/languages/xquery",
      "npm:highlight.js@8.7.0/lib/languages/zephir",
      "npm:marked@0.3.5",
      "npm:js-yaml@3.2.7",
      "npm:codemirror@5.6.0/mode/xml/xml",
      "npm:codemirror@5.6.0/mode/meta",
      "github:jspm/nodelibs-buffer@0.1.0",
      "github:jspm/nodelibs-process@0.1.1/index",
      "npm:marked@0.3.5/lib/marked",
      "npm:js-yaml@3.2.7/index",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:process@0.10.1",
      "npm:js-yaml@3.2.7/lib/js-yaml",
      "npm:buffer@3.4.3",
      "npm:process@0.10.1/browser",
      "npm:js-yaml@3.2.7/lib/js-yaml/loader",
      "npm:js-yaml@3.2.7/lib/js-yaml/dumper",
      "npm:js-yaml@3.2.7/lib/js-yaml/type",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema/json",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema/failsafe",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema/core",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema/default_safe",
      "npm:js-yaml@3.2.7/lib/js-yaml/schema/default_full",
      "npm:js-yaml@3.2.7/lib/js-yaml/exception",
      "npm:js-yaml@3.2.7/lib/js-yaml/common",
      "npm:js-yaml@3.2.7/lib/js-yaml/mark",
      "npm:buffer@3.4.3/index",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/null",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/int",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/bool",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/float",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/str",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/seq",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/map",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/merge",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/timestamp",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/binary",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/omap",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/pairs",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/set",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/js/undefined",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/js/regexp",
      "npm:js-yaml@3.2.7/lib/js-yaml/type/js/function",
      "npm:ieee754@1.1.6",
      "npm:is-array@1.0.1",
      "npm:base64-js@0.0.8",
      "npm:esprima@2.0.0",
      "npm:ieee754@1.1.6/index",
      "npm:is-array@1.0.1/index",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:esprima@2.0.0/esprima"
    ]
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.4",
    "codemirror": "npm:codemirror@5.6.0",
    "emojify.js": "npm:emojify.js@1.1.0",
    "highlight.js": "npm:highlight.js@8.7.0",
    "marked": "npm:marked@0.3.5",
    "meta-marked": "npm:meta-marked@0.3.3",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.4.3"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:argparse@1.0.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "lodash": "npm:lodash@3.10.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "sprintf-js": "npm:sprintf-js@1.0.3",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:buffer@3.4.3": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:codemirror@5.6.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:emojify.js@1.1.0": {
      "path": "github:jspm/nodelibs-path@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:esprima@2.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:highlight.js@8.7.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:js-yaml@3.2.7": {
      "argparse": "npm:argparse@1.0.2",
      "esprima": "npm:esprima@2.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:meta-marked@0.3.3": {
      "js-yaml": "npm:js-yaml@3.2.7",
      "marked": "npm:marked@0.3.5"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
